name: Movecraft-Cannons
version: ${project.version}
main: net.tylers1066.movecraftcannons.MovecraftCannons
api-version: 1.19
depend: [Movecraft, Cannons, SquadronsReloaded, Towny]
softdepend: [Movecraft-Combat]
authors: [TylerS1066]
description: Integration between Movecraft and Cannons
commands:
  aim:
    description: Aim cannons facing in the direction you are looking at while on a ship.
  fire:
    description: Fire cannons facing in the direction you are looking at while on a ship.
  lockon:
    description: Selects a target for homing projectiles.